apiVersion: v1
kind: Service
metadata:
  name: {{ template "schema-registry.fullname" . }}-headless
  labels:
    app: {{ template "schema-registry.name" . }}
    chart: {{ template "schema-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8081
      name: schema-registry
  clusterIP: None
  selector:
    app: {{ template "schema-registry.name" . }}
    release: {{ .Release.Name }}