apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-kafka-configmap
data:
  kafka_bootstrapServers: {{ template "kafka.fullname" . }}-headless:9092
  spring_kafka_bootstrapservers: {{ template "kafka.fullname" . }}-headless:9092
  kafka_replicationFactor: {{ .Values.replicationFactor | quote }}
  kafka_inSyncReplica: {{ .Values.inSyncReplica | quote }}