k8ssandra:
  enabled: true
  cassandra:
    version: "3.11.10"
    cassandraLibDirVolume:
      storageClass: local-path
      size: 5Gi
    allowMultipleNodesPerWorker: true
    heap:
      size: 1G
      newGenSize: 1G
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    datacenters:
      - name: dc1
        size: 1
        racks:
          - name: default
    ingress:
      enabled: true
  kube-prometheus-stack:
    grafana:
      enabled: false
      adminUser: admin
      adminPassword: admin123
    prometheus:
      enabled: false
  medusa:
    enabled: false
  reaper:
    enabled: false
  stargate:
    enabled: false
    replicas: 1
    heapMB: 256
    cpuReqMillicores: 200
    cpuLimMillicores: 1000