fsmpekkokafka:
  enabled: true
  zookeeper:
    #image: k3d-fsm-akka.registry:5555/nxt/confluentinc/cp-zookeeper
    #imageTag: 6.2.2-ubi8
    servers: 1
    heapOptions: -Xms256M -Xmx512M
    persistence:
      dataDirSize: 1Gi
      dataLogDirSize: 1Gi
    resources:
      limits:
        cpu: 0.5
        memory: 1G
      requests:
        cpu: 0.5
        memory: 1G
  kafka:
    #image: k3d-fsm-akka.registry:5555/nxt/confluentinc/cp-server
    #imageTag: 6.2.2-ubi8
    brokers: 1
    configurationOverrides:
      "offsets.topic.replication.factor": "1"
      "default.replication.factor": "1"
      "confluent.metrics.reporter.topic.replicas": "1"
      "confluent.reporters.telemetry.auto.enable": "false"
      "confluent.balancer.topic.replication.factor": "1"
      "confluent.license.topic.replication.factor": "1"
    heapOptions: "-Xms2G -Xmx2G"
    persistence:
      storageClass: ""
      size: 5Gi
      disksPerBroker: 1
    resources:
      limits:
        cpu: 1
        memory: 3G
      requests:
        cpu: 1
        memory: 3G
    replicationFactor: 1
    inSyncReplica: 1
  schema-registry:
    #image: k3d-fsm-akka.registry:5555/nxt/confluentinc/cp-schema-registry
    #imageTag: 6.2.2-ubi8
    replicaCount: 1
    heapOptions: -Xms512M -Xmx512M
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 1G
  kafka-connect:
    enabled: false
    heapOptions: -Xmx512M -Xmx512M
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 1G
    configurationOverrides:
      "config.storage.replication.factor": "1"
      "offset.storage.replication.factor": "1"
      "status.storage.replication.factor": "1"
