apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.clientPort }}
      name: client
    {{- if .Values.prometheus.jmx.enabled }}
    - name: metrics
      port: {{ .Values.prometheus.jmx.port }}
    {{- end }}
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
