apiVersion: v2
appVersion: "1.0"
description: A Helm chart for FSM Akka Kafka
name: fsmpekkokafka
version: 1.0.0
dependencies:
  - name: kafka
    version: 1.0.0
    condition: kafka.enabled
  - name: zookeeper
    version: 1.0.0
    condition: zookeeper.enabled
  - name: schema-registry
    version: 1.0.0
    condition: schema-registry.enabled
  - name: kafka-connect
    version: 1.0.0
    condition: kafka-connect.enabled