{{- if .Values.projects.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fsm-akka-4eyes-project
  namespace: argocd
spec:
  description: "Project for FSM Akka Four Eyes Eventsourcing Application"
  destinations:
    - namespace: fsmakka
      server: https://kubernetes.default.svc
    - namespace: nexus
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - fsmakka
    - nexus
  sourceRepos:
    - "https://github.com/mehmetsalgar/Akka-Finite-State-Machine.git"
    - "https://github.com/mehmetsalgar/customer-relationship-adapter.git"
    - "https://sonatype.github.io/helm3-charts/"
    - "http://fsmakka.salgar.org/repository/fsm-akka-helm/"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
{{- end -}}