POST http://localhost:56677/creditsm/_search?pretty
Content-Type: application/json

{
  "query": {
    "match": {
      "state": "CREDIT_REJECTED"
    }
  },
  "fields": ["creditUuid", "state", "credit*"],
  "_source": false
}