traefik:
  enabled: true
  logs:
    general:
      level: DEBUG
  experimental:
    kubernetesGateway:
      enabled: false
  providers:
    kubernetesCRD:
      namespaces:
        - default
        - traefik
        - fsmakka
        - nexus
    kubernetesIngress:
      namespaces:
        - default
        - traefik
        - fsmakka
        - nexus
  ports:
    traefik:
      expose: true
      nodePort: 32090
    web:
      nodePort: 32080
    websecure:
      nodePort: 32443
    cassandra:
      expose: true
      port: 9042
      nodePort: 32091
    cassandrasecure:
      expose: true
      port: 9142
      nodePort: 32092
    sg-graphql:
      expose: true
      port: 8880
      nodePort: 30080
    sg-auth:
      expose: true
      port: 8881
      nodePort: 30081
    sg-rest:
      expose: true
      port: 8882
      nodePort: 30082
    elasticsearch:
      expose: true
      port: 9200
      nodePort: 32193
    nexus:
      expose: true
      port: 8081
      nodePort: 31081
  service:
    type: NodePort
  ingressRoute:
    dashboard:
      enabled: false
  additionalArguments:
    - --api.insecure=true
    - --serversTransport.insecureSkipVerify=true
    - --log.level=debug